default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: 123

development:
  <<: *default
  database: qshD

test:
  <<: *default
  database: qshT

production:
  <<: *default
  database: qshP
