# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: 123456

development:
  <<: *default
  database: qshD

test:
  <<: *default
  database: qshT

production:
  <<: *default
  database: qshP
